// ── Browser host (styles-design §8 follow-on) ────────────────────────────────
// The headless runtime (runtime.ts + `interactive`) produces a patch stream; this
// module is its BROWSER side: a vanilla-JS patch applier (the DOM counterpart of
// `diff`) plus a self-contained HTML page that mounts the initial render and
// REPLAYS a recorded event→patch session against the real DOM. It proves the patch
// protocol drives a live DOM with the same prop→CSS rules as `render.ts`.
//
// What it is NOT (yet): a fully live host — events do not re-run `view()` in the
// browser, because that needs a velve→JS compiler (or the interpreter shipped to
// the browser). The recorded session is generated by the Node interpreter; the
// page replays it. That live-execution compiler is the documented remaining gap.
//
// `APPLIER_JS` is plain JS, used two ways from ONE source: embedded in the emitted
// page, and `eval`-able in Node against a DOM shim for unit testing (see
// dom_applier_test.mjs).

export const APPLIER_JS = String.raw`
// prop -> [cssProperty, isPx] — mirrors render.ts CSS map so styles match the SSR.
const VELVE_CSS = {
  width:["width",1], height:["height",1], padding:["padding",1], margin:["margin",1],
  gap:["gap",1], radius:["border-radius",1], background:["background",0], color:["color",0],
  size:["font-size",1], weight:["font-weight",0], font:["font-family",0],
  align:["align-items",0], justify:["justify-content",0], opacity:["opacity",0],
  grow:["flex-grow",0], shrink:["flex-shrink",0], basis:["flex-basis",1], alignSelf:["align-self",0],
};
function velvePx(v){ return /^-?\d+(\.\d+)?$/.test(v) ? v + "px" : v; }
// Navigate a patch path ("0/1") over ELEMENT children (matches diff's childList for
// element-only trees — the keyless caveat applies to mixed text/element children).
function velveNodeAt(root, path){
  if(path === "") return root;
  let n = root;
  for(const seg of path.split("/")){ if(!n) return null; n = n.children[+seg]; }
  return n;
}
function velveApply(root, p){
  const n = velveNodeAt(root, p.path);
  if(!n) return;
  switch(p.op){
    case "setProp": {
      const m = VELVE_CSS[p.name];
      if(m) n.style.setProperty(m[0], m[1] ? velvePx(p.value) : p.value);
      else n.setAttribute(p.name, p.value);
      break;
    }
    case "removeProp": {
      const m = VELVE_CSS[p.name];
      if(m) n.style.removeProperty(m[0]); else n.removeAttribute(p.name);
      break;
    }
    case "setText": n.textContent = p.text; break;
    case "replace": n.outerHTML = p.html; break;
    case "insertChild": {
      const tmp = document.createElement("template");
      tmp.innerHTML = p.html.trim();
      const ref = n.children[p.index] || null;
      n.insertBefore(tmp.content.firstChild, ref);
      break;
    }
    case "removeChild": { const c = n.children[p.index]; if(c) c.remove(); break; }
    case "moveChild": {
      const cur = [...n.children].find(c => c.id === p.key);
      if(cur) n.insertBefore(cur, n.children[p.to] || null);
      break;
    }
  }
}
`;

export interface HostStep { label: string; patches: unknown[]; }

// A complete, self-contained HTML page: initial render + applier + recorded session
// + a replay driver (a "next step" button applies that step's patches to the DOM).
export function domHostPage(initialHtml: string, session: HostStep[], title: string): string {
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>${title}</title>
<style>body{font:14px system-ui;margin:24px}#velve-log{color:#666;white-space:pre-wrap}</style>
</head><body>
<h3>${title} — retained-runtime replay (${session.length} step${session.length === 1 ? "" : "s"})</h3>
<div id="velve-root">${initialHtml}</div>
<p><button id="velve-step">▶ next step</button> <button id="velve-all">▶▶ all</button></p>
<pre id="velve-log"></pre>
<script>
${APPLIER_JS}
const SESSION = ${JSON.stringify(session)};
let i = 0;
const root = document.getElementById("velve-root").firstElementChild;
const log = document.getElementById("velve-log");
function step(){
  if(i >= SESSION.length){ log.textContent += "\\n(done)"; return false; }
  const s = SESSION[i++];
  for(const p of s.patches) velveApply(root, p);
  log.textContent += "\\n" + s.label + " — " + s.patches.length + " patch(es)";
  return true;
}
document.getElementById("velve-step").onclick = step;
document.getElementById("velve-all").onclick = () => { while(step()){} };
</script>
</body></html>`;
}
